NAME = program
SRC = WindowProcedure.cpp open_file.cpp save_file.cpp header_maker.cpp AddControls.cpp AddMenus.cpp dialog_window.cpp

all: $(NAME)

$(NAME):
	gcc $(SRC) -o $(NAME) -lcomdlg32 -lstdc++
