CODESG SEGMENT PARA 'Code'
ASSUME CS:CODESG, SS:CODESG, DS:CODESG
ORG 100H
main: jmp BEGIN
a dw 25h
b dw 17h
c dw 0Fh
BEGIN PROC NEAR
MOV	AX, a; ENTER A IN AX REGISTER
MOV	BX, b;
CMP	AX, BX; COMPARE AX AND BX
JG	L1; IF AX>BX
MOV	AX, c
JMP 	SHORT L2;
L1:SUB	AX,BX; A-B
L2:	RET
BEGIN ENDP
CODESG ENDS
END MAIN